// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrUTzMk8uqmZCdQxLuTCk3i4wGn0T-Uig',
    appId: '1:212690100293:web:2b75ff01acf4fd20d1832c',
    messagingSenderId: '212690100293',
    projectId: 'flutterplants',
    authDomain: 'flutterplants.firebaseapp.com',
    storageBucket: 'flutterplants.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6nsFsH24IY7YKSrgH5sFxxoyoAf3MTqI',
    appId: '1:212690100293:android:90f20926772731a6d1832c',
    messagingSenderId: '212690100293',
    projectId: 'flutterplants',
    storageBucket: 'flutterplants.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBahfPsjR0J19QtyaSXJudiW9jPghwDF2E',
    appId: '1:212690100293:ios:84a3250f4818d13bd1832c',
    messagingSenderId: '212690100293',
    projectId: 'flutterplants',
    storageBucket: 'flutterplants.appspot.com',
    iosBundleId: 'com.example.flutterPlants',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBahfPsjR0J19QtyaSXJudiW9jPghwDF2E',
    appId: '1:212690100293:ios:c792d2f02af03a9fd1832c',
    messagingSenderId: '212690100293',
    projectId: 'flutterplants',
    storageBucket: 'flutterplants.appspot.com',
    iosBundleId: 'com.example.flutterPlants.RunnerTests',
  );
}
